name: dswd_slp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  google_fonts: ^6.3.2
  go_router: ^17.0.0
  open_file: ^3.5.10
  provider: ^6.1.5+1
  sqflite: ^2.3.0
  crypto: ^3.0.7
  intl: ^0.20.2
  path: ^1.9.0
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
